version: '3.8'
services:

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}
      - GOOGLE_SHEETS_SCOPE=${GOOGLE_SHEETS_SCOPE}
    env_file:
      - .env
    ports:
      - "5000:5000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
